export const products = [
  {
    id: 1,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: 500,
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
    country: "UK",
    sex: 'Women',
    productType: 'Parfum',
    smellType: 'восточные, цветочные',
    начальнаяНота: 'Жасмин',
    нотаСердца: 'Персик, Роза',
    конечнаяНота: 'Амбра, Пачули',
    value: '200$',
    code: '14141',
    brand: 'Burberry',
    description: 'Восточные ароматы с цветочными оттенками всегда будут актуальны среди тех, кто любит привлекать внимание окружающих и выражать себя посредством запахов. Парфюмированная вода Burberry My Burberry Black станет той маленькой роскошью, которую вы сможете позволить себе каждый день. Мягкое и ненавязчивое благоухание персика и розы создают чарующий дует, который убаюкивает, уносит в мир грез и приятных воспоминаний. Такой фруктово-цветочный сад, сдобренный утонченными жасминовыми оттенками точно отражает всю суть женского обаяния и очарования. Приземистые ноты амбры и пачули, сливаясь с жизнерадостными тонами парфюма, создают запоминающийся и яркий шлейф. Это аромат утонченной леди, которая буквально купается в собственной красоте и великолепии. Ей не нужно подтверждение своего великолепия, потому что восторженные толпы поклонников говорят намного красноречивее слов.'
  },
  {
    id: 2,
    name: 'Guess',
    type: "fragrancies",
    productType: 'Water',
    quantity: 50,
    price: 322,
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
    brand: 'Guess',
  },
  {
    id: 3,
    name: 'Lacoste',
    type: "fragrancies",
    productType: 'SweetWater',
    quantity: 50,
    price: 132,
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
    brand: 'Lacoste',
  },
  {
    id: 4,
    name: 'Lacoste',
    type: "fragrancies",
    productType: 'Parfum',
    quantity: 50,
    price: 41,
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
    brand: 'Lacoste',
  },
  {
    id: 5,
    name: 'TH',
    type: "fragrancies",
    productType: 'SweetWater',
    quantity: 50,
    price: 5052510,
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
    brand: 'TH',
  },
  {
    id: 6,
    name: 'Gucci',
    type: "fragrancies",
    productType: 'Water',
    quantity: 50,
    price: 41414,
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
    brand: 'Gucci',
  },
  {
    id: 7,
    name: 'YL',
    type: "fragrancies",
    productType: 'SweetWater',
    quantity: 50,
    price: 57400,
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
    brand: 'YL',
  },
  {
    id: 8,
    name: 'LV',
    type: "fragrancies",
    productType: 'Water',
    quantity: 50,
    price: 3,
    brand: 'LV',
    img: ["https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg", 'https://u.makeup.com.ua/n/nv/nv58d9az3ukf.jpg', 'https://u.makeup.com.ua/t/tr/trvhbjgtp5vz.jpg', 'https://u.makeup.com.ua/a/ap/apusvqdqujjl.jpg'],
  },
]