export const products = [
  {
    id: 1,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg",
  },
  {
    id: 2,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg",
  },
  {
    id: 3,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/0/0h/0harpst4no05.jpg",
  },
  {
    id: 4,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/0/0h/0harpst4no05.jpg",
  },
  {
    id: 5,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg",
  },
  {
    id: 6,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/0/0h/0harpst4no05.jpg",
  },
  {
    id: 7,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/g/gj/gj9mojcjeaga.jpg",
  },
  {
    id: 8,
    name: 'Burberry My Burberry Black',
    type: "fragrancies",
    quantity: 50,
    price: '500$',
    img: "https://u.makeup.com.ua/0/0h/0harpst4no05.jpg",
  },
]